# -*- mode:python; coding:utf-8; -*-

Import('boostEnvironment', 'catchEnvironment')

boostTest = boostEnvironment.Program('boost.cpp')
catchTest = catchEnvironment.Program('catch.cpp')

Return('boostTest', 'catchTest')
