# -*- mode:python; coding:utf-8; -*-

Import('boostEnvironment', 'googleEnvironment', 'cuteEnvironment', 'catchEnvironment')

boostTest = boostEnvironment.Program('boost.cpp')
googleTest = googleEnvironment.Program('google.cpp')
cuteTest = cuteEnvironment.Program('cute.cpp')
catchTest = catchEnvironment.Program('catch.cpp')

Return('boostTest', 'googleTest', 'cuteTest', 'catchTest')
